SELECT ID, 
CASE WHEN R/N<=0.25 THEN 'CRITICAL'
WHEN R/N<=0.5 THEN 'HIGH'
WHEN R/N<=0.75 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM (
SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS R,
(SELECT COUNT(*) FROM ECOLI_DATA) AS N
 FROM ECOLI_DATA) AS subquery ORDER BY ID;