-- 코드를 작성해주세요

SELECT QUARTER, COUNT(QUARTER) AS ECOLI_COUNT FROM (SELECT CASE WHEN MONTH(DIFFERENTIATION_DATE) < '4' THEN '1Q'
WHEN MONTH(DIFFERENTIATION_DATE) >='4' AND MONTH(DIFFERENTIATION_DATE)<'7' THEN '2Q'
WHEN MONTH(DIFFERENTIATION_DATE)>='7' AND MONTH(DIFFERENTIATION_DATE)<'10' THEN '3Q'
ELSE '4Q' END AS QUARTER FROM ECOLI_DATA) AS TEST GROUP BY QUARTER;