/* HR_GRADE: score로 GRADE 계산 -> 평균 내야함, inner join EMP_NO
HR_EMPLOYEES: SAL*grade
*/


SELECT S.EMP_NO, H.EMP_NAME, S.GRADE, S.RATIO*H.SAL AS BONUS FROM HR_EMPLOYEES H JOIN 
(SELECT EMP_NO, CASE WHEN GRADE="S" THEN 0.2
WHEN GRADE="A" THEN 0.15
WHEN GRADE="B" THEN 0.1
ELSE 0 END AS RATIO, GRADE FROM

(SELECT EMP_NO, CASE WHEN AVG(SCORE)>=96 THEN "S" 
WHEN AVG(SCORE)<96 AND AVG(SCORE)>=90 THEN "A" 
WHEN AVG(SCORE)<90 AND AVG(SCORE)>=80 THEN "B"
ELSE "C" END AS GRADE
FROM HR_GRADE GROUP BY EMP_NO) AS HR_SCORE) S ON S.EMP_NO=H.EMP_NO;


