# 연도별 가장 큰 대장균 크기 table 만들기
# 거기서 최대값 빼고, 해당 연도별 정렬하기

SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (B.MAX_SIZE-A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID FROM ECOLI_DATA
AS A LEFT JOIN
(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B ON YEAR(A.DIFFERENTIATION_DATE)=B.YEAR
ORDER BY YEAR(A.DIFFERENTIATION_DATE), (B.MAX_SIZE-A.SIZE_OF_COLONY)

